apiVersion: v1
kind: Service
metadata:
  name: '{{.Values.dep-service .serviceName}}'
spec:
  selector:
    app: '{{.Values.dep-service .serviceName}}'
  ports:
  - name: http
    port: 80
    targetPort: '{{.Values.dep-service .containerPort}}'
  type: ClusterIP
