apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: '{{.Values.appName}}'
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
  - host: '{{.Values.hostName}}'
    http:
      paths:
      - path: /{{.Values.dep-service .serviceName}}(/|$)(.*)
        pathType: Prefix
        backend:
          service:
            name: '{{.Values.dep-service .serviceName}}'
            port:
              name: http
